"""Turn one RPG Maker 2000/2003 game folder into a self-contained, embeddable web build."""
from __future__ import annotations

import html as _html
import json
import re
import shutil
from pathlib import Path

from . import gencache, player_fetch, soundfont_fetch, staging

__version__ = "0.1.0"
PLAYER_FILES = ("index.js", "index.wasm")
# Most RPG Maker 2000/2003 games use MIDI music, which is silent without a
# soundfont. By default download a free one (see soundfont_fetch) so audio works
# out of the box; pass soundfont=None to skip, or a path to use a custom .sf2.
AUTO_SOUNDFONT = "auto"


class BuildError(Exception):
    pass


# Service worker: games/ files are cache-first, the shell is network-first.
# Crucial for correctness, not just offline: the EasyRPG web player streams
# many asset requests while running, and some silently fail against a plain
# static server (no 404, no placeholder — assets just go missing). The precache
# step below fills this cache up-front via robust fetches; the SW then serves
# every asset cache-first, so the player never hits an unreliable live request.
SW_JS = """\
// Generated by rpgmaker-to-web.
// games/ assets -> cache-first (filled up-front by the page's precache step).
// shell (HTML/JS/WASM) -> network-first (always fresh online, falls back to cache offline).
const CACHE = 'easyrpg-games';

self.addEventListener('install', () => self.skipWaiting());

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

function isGameAsset(req) {
  try { return new URL(req.url).pathname.includes('/games/'); }
  catch (err) { return false; }
}

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  if (isGameAsset(e.request)) {
    e.respondWith(
      caches.match(e.request).then((hit) => {
        if (hit) return hit;
        return fetch(e.request).then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(e.request, copy)).catch(() => {});
          return res;
        });
      })
    );
  } else {
    e.respondWith(
      fetch(e.request).then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(e.request, copy)).catch(() => {});
        return res;
      }).catch(() =>
        caches.match(e.request).then((hit) => {
          if (hit) return hit;
          if (e.request.mode === 'navigate') return caches.match('index.html');
          return Response.error();
        })
      )
    );
  }
});
"""

SW_REGISTER = (
    "<script>if('serviceWorker' in navigator){"
    "window.addEventListener('load',function(){"
    "navigator.serviceWorker.register('service-worker.js');});}</script>\n"
)

# Audio unlock: browsers start every AudioContext suspended until a real user
# gesture (autoplay policy). The player doesn't reliably resume on interaction,
# so locally you'd get partial/no sound (online "works" only because a trusted,
# often-visited origin gets autoplay leeway). This shim runs BEFORE the player,
# wraps the AudioContext constructor to track every context the player creates,
# and resumes them all on the first click/keypress/touch — so a single normal
# interaction (which you do anyway to play) gives full music + SFX everywhere.
AUDIO_UNLOCK = (
    "<script>(function(){var ctxs=[];function track(name){var O=window[name];"
    "if(!O)return;function W(o){var c=new O(o);try{ctxs.push(c);}catch(e){}return c;}"
    "W.prototype=O.prototype;try{window[name]=W;}catch(e){}}"
    "track('AudioContext');track('webkitAudioContext');"
    "function resume(){for(var i=0;i<ctxs.length;i++){var c=ctxs[i];"
    "if(c&&c.state!=='running'&&c.resume){try{c.resume();}catch(e){}}}}"
    "['pointerdown','mousedown','touchstart','keydown','click'].forEach(function(ev){"
    "window.addEventListener(ev,resume,true);});})();</script>\n"
)


def _precache_script(slug: str) -> str:
    """Page script that downloads precache-<slug>.json into the easyrpg-games cache.

    Runs six parallel workers; shows a small progress bar while filling the cache
    so the player (served cache-first by the SW) gets every asset reliably."""
    slug_js = json.dumps(slug)
    return (
        "\n<style>#dl{position:fixed;left:0;right:0;bottom:0;background:#1f2937;"
        "padding:8px 14px calc(8px + env(safe-area-inset-bottom));"
        "font:13px -apple-system,sans-serif;color:#cbd5e1;z-index:9999}"
        "#dltrack{height:5px;background:#374151;border-radius:3px;overflow:hidden}"
        "#dlbar{height:100%;width:0;background:#2563eb;transition:width .2s}"
        "#dltext{display:block;margin-top:5px}</style>"
        '\n<div id="dl" hidden><div id="dltrack"><div id="dlbar"></div></div><span id="dltext"></span></div>'
        '\n<script>(function(){if(!("caches" in window))return;var SLUG=' + slug_js + ";"
        'fetch("precache-"+SLUG+".json").then(function(r){return r.json();}).then(function(files){'
        'var box=document.getElementById("dl"),bar=document.getElementById("dlbar"),'
        'txt=document.getElementById("dltext");'
        'caches.open("easyrpg-games").then(function(cache){'
        "var total=files.length,done=0,idx=0;"
        'function show(){box.hidden=false;var pct=total?Math.round(done/total*100):100;'
        'bar.style.width=pct+"%";'
        'if(done>=total){txt.textContent="\\u2713 Ready to play offline";'
        "setTimeout(function(){box.hidden=true;},3000);}"
        'else{txt.textContent="Caching game\\u2026 "+pct+"% ("+done+"/"+total+")";}}'
        "show();"
        "function worker(){return (async function(){while(idx<total){var f=files[idx++];"
        "try{if(!(await cache.match(f)))await cache.add(f);}catch(e){}done++;show();}})();}"
        "var n=Math.min(6,total)||1,ws=[];for(var i=0;i<n;i++)ws.push(worker());"
        "Promise.all(ws);});}).catch(function(){});})();</script>\n"
    )


def slugify(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return s or "game"


def _validate(game_dir: Path) -> None:
    if not game_dir.is_dir():
        raise BuildError(f"Game folder not found: {game_dir}")
    if not any((game_dir / n).exists() for n in ("RPG_RT.ldb", "RPG_RT.lmt")):
        raise BuildError(
            f"Not an RPG Maker 2000/2003 game (missing RPG_RT.ldb/.lmt): {game_dir}")


def build(game_dir, out="dist", title=None, soundfont=AUTO_SOUNDFONT,
          player_cache=".player-cache", player_url=player_fetch.PLAYER_URL,
          soundfont_url=soundfont_fetch.SOUNDFONT_URL,
          refresh_player=False, log=print) -> Path:
    """Build `game_dir` into `out/` (player + staged game + index.json + play page).

    `soundfont`: "auto" (default) downloads a free soundfont for MIDI music;
    None omits it (MIDI silent); or pass a path to a custom .sf2."""
    game_dir = Path(game_dir)
    out = Path(out)
    _validate(game_dir)
    name = title or game_dir.name
    slug = slugify(game_dir.name)

    if soundfont == AUTO_SOUNDFONT:
        log("Downloading soundfont (GeneralUser GS)…")
        soundfont = soundfont_fetch.ensure_soundfont(player_cache, url=soundfont_url)
    elif soundfont and not Path(soundfont).exists():
        log(f"Warning: soundfont not found ({soundfont}); building without music.")
        soundfont = None

    log("Downloading EasyRPG web player…")
    player_dir = player_fetch.ensure_player(player_cache, url=player_url, refresh=refresh_player)

    staging.force_rmtree(out)
    out.mkdir(parents=True)
    for fname in PLAYER_FILES:
        shutil.copy2(player_dir / fname, out / fname)

    log("Staging game…")
    staging.stage_game(game_dir, out / "games" / slug, soundfont=soundfont)

    log("Generating index.json…")
    gencache.write_index(out / "games" / slug)

    log("Writing service worker + precache manifest…")
    (out / "service-worker.js").write_text(SW_JS, encoding="utf-8")
    game_dir = out / "games" / slug
    game_files = sorted(
        p.relative_to(out).as_posix() for p in game_dir.rglob("*") if p.is_file()
    )
    shell = ["index.js", "index.wasm", "index.html"]
    (out / ("precache-" + slug + ".json")).write_text(
        json.dumps(shell + game_files, ensure_ascii=False), encoding="utf-8"
    )

    log("Writing play page…")
    template = (player_dir / "index.html").read_text(encoding="utf-8")
    page = template.replace("game: undefined", "game: " + json.dumps(slug))
    page = re.sub(r"<title>.*?</title>", "<title>" + _html.escape(name) + "</title>",
                  page, count=1, flags=re.S)
    # Inject the SW registration + audio unlock into <head> and the precache step
    # before </body>. SW+precache make every asset load reliably (see SW_JS);
    # the audio unlock makes sound work after one interaction (see AUDIO_UNLOCK).
    page = page.replace("</head>", AUDIO_UNLOCK + SW_REGISTER + "</head>", 1)
    dl = _precache_script(slug)
    page = page.replace("</body>", dl + "</body>", 1) if "</body>" in page else page + dl
    (out / "index.html").write_text(page, encoding="utf-8")

    log(f"Done: {out}")
    return out


def iframe_snippet(src: str = "index.html", width: int = 640, height: int = 480) -> str:
    return (f'<iframe src="{src}" width="{width}" height="{height}" '
            'style="border:0;aspect-ratio:4/3;max-width:100%" allowfullscreen></iframe>')
